name: Java CI/CD Pipeline

on:
  push:
    branches: [main]  # Trigger workflow on push to the main branch
  pull_request:
    branches: [main]  # Trigger workflow on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Using the latest Ubuntu runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Check out the repository

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Use Eclipse Temurin JDK
        java-version: '17'
        cache: 'maven'  # Enable Maven cache to speed up dependency resolution

    - name: Build with Maven (Debugging)
      run: mvn clean install -X  # Run `mvn clean install` and enable debug output for troubleshooting

    - name: List target directory contents (debugging)
      run: ls -alh target/  # List contents of the target directory to check if the .jar file exists

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3  # Explicitly use the stable version of the action
      with:
        name: my-java-app  # Artifact name
        path: target/*.jar  # Path to the .jar file to upload
