name: Java CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Trigger on push to the main branch
  pull_request:
    branches: [ main ]  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Using the latest Ubuntu runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Using Eclipse Temurin JDK
        java-version: '17'
        cache: 'maven'

    - name: Build and Test with Maven
      run: mvn clean package  # This should create the .jar in target/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-java-app  # Name of the artifact to be uploaded
        path: target/*.jar  # Path to the generated .jar file
