name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from your repository

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use Node.js version 14 (or modify based on your project)

    - name: Install dependencies
      run: npm install  # Run this if you're working with Node.js, modify for your project

    - name: Build the project
      run: npm run build  # Modify to your build script (e.g., for a Node.js project)

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: build-artifact
        path: ./build/*  # Replace with the correct path to your build output
